site_name: MAPI Documentations
site_url: "https://protomapi.readthedocs.io/en/latest/"
# use_directory_urls: false
# plugins: []

nav:
  - Index Page: 
    - index: "index.md"
  - Config Model:
    - config: "pages/config/config.md"
  - Invoice Models:
    - pre_invoice: "pages/invoice/pre_invoice.md"
    - invoice: "pages/invoice/invoice.md"
    - all_invoice_mid: "pages/invoice/all_invoice_mid_base.md"
    - all_invoice: "pages/invoice/all_invoice.md"
  - Log Model:
    - log: "pages/log/log.md"
  - Person Models:
    - person: "pages/person/person.md"
    - temp_person: "pages/person/temp_person.md"
    - person_group: "pages/person/person_group.md"
    - person_tel: "pages/person/person_tel.md"
    - portion: "pages/person/portion.md"
  - Product Models:
    - barcode: "pages/product/barcode.md"
    - price_level: "pages/product/price_level.md"
    - price: "pages/product/price.md"
    - product_category: "pages/product/product_category.md"
    - product: "pages/product/product.md"
    - repository: "pages/product/repository.md"
    - unit: "pages/product/unit.md"
  - User Models:
    - group: "pages/user/group.md"
    - permission: "pages/user/permission.md"
    - user: "pages/user/user.md"

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
    sticky_navigation: true

  
